USE [master]
GO

/****** Object:  Database [Cascade.Assessment.Db]    Script Date: 3/25/2022 8:23:59 PM ******/
CREATE DATABASE [Cascade.Assessment.Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cascade.Assessment.Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Cascade.Assessment.Db_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cascade.Assessment.Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Cascade.Assessment.Db_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cascade.Assessment.Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cascade.Assessment.Db] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET ARITHABORT ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET RECOVERY FULL 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET  MULTI_USER 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [Cascade.Assessment.Db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Cascade.Assessment.Db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Cascade.Assessment.Db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Cascade.Assessment.Db] SET  READ_WRITE 
GO


